### ISSUE TITLE
Add support for the ATSAME51 Curiosity Nano

### ISSUE THREAD

**Issue by JakeSays** [Microchip-MPLAB-Harmony/bsp#6]
Please add support for the ATSAME51 Curiosity Nano dev board.

**Comment by dsettu** [comment]
File internal ticket to add support for it in v3.10 release.

**Comment by JakeSays** [comment]
@dsettu can you give me a time frame for v3.10?

**Comment by dsettu** [comment]
@JakeSays ,v3.10 may get released by Aug'21.

**Comment by JakeSays** [comment]
@dsettu what?? you guys only release once a YEAR?

**Comment by dsettu** [comment]
@JakeSays , We do dot release for critical defects. Major releases are scheduled 5-6months. 
v3.9 was released yesterday,  hence v3.10 may get released by Aug'21.
